### PR TITLE
WIP: add volume api

### PR DESCRIPTION
**Pull request by Lange**
Hi there!

Thanks for making this package! I found it to be the easiest DO API wrapper to use by far.

I needed to use the [Block Storage API](https://developers.digitalocean.com/documentation/v2/#block-storage), so I took a crack at adding those methods and tests for those methods. However, 5 of the tests are failing. I'm not completely sure as to why. D'you think you could help point me in the right direction?

Thanks again,
Alex

### CODE REVIEW

**Comment by lukeed** [comment]
Hey thanks!

I just got back to my desk. I'll take a look now, but honestly, I haven't touched this repo in ages.

**Comment by lukeed** [comment]
Oh, simple. From Travis docs re: environment variables:

> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

The tests will run once merged. Your commit says "WIP", so is this ready @Lange?

**Comment by Lange** [comment]
Sorry, I should clarify, these tests fail locally with my own DigitalOcean token provided via the `DOTOKEN` environment variable. This is not ready to merge.

**Comment by lukeed** [comment]
Ah, got it. Will check it out. 👍

**Comment by lukeed** [comment]
Thanks @Lange !

**Pull request merged**
